# -*- coding: utf-8 -*-
"""股票分析Agent Prompt模板包"""

from .market_analyst import SYSTEM_PROMPT as MARKET_ANALYST_SYSTEM, USER_TEMPLATE as MARKET_ANALYST_USER
from .fundamentals_analyst import SYSTEM_PROMPT as FUNDAMENTALS_ANALYST_SYSTEM, USER_TEMPLATE as FUNDAMENTALS_ANALYST_USER
from .news_analyst import SYSTEM_PROMPT as NEWS_ANALYST_SYSTEM, USER_TEMPLATE as NEWS_ANALYST_USER
from .sentiment_analyst import SYSTEM_PROMPT as SENTIMENT_ANALYST_SYSTEM, USER_TEMPLATE as SENTIMENT_ANALYST_USER
from .bull_researcher import SYSTEM_PROMPT as BULL_RESEARCHER_SYSTEM, USER_TEMPLATE as BULL_RESEARCHER_USER
from .bear_researcher import SYSTEM_PROMPT as BEAR_RESEARCHER_SYSTEM, USER_TEMPLATE as BEAR_RESEARCHER_USER
from .research_manager import SYSTEM_PROMPT as RESEARCH_MANAGER_SYSTEM, USER_TEMPLATE as RESEARCH_MANAGER_USER
from .trader import SYSTEM_PROMPT as TRADER_SYSTEM, USER_TEMPLATE as TRADER_USER
from .risky_debator import SYSTEM_PROMPT as RISKY_DEBATOR_SYSTEM, USER_TEMPLATE as RISKY_DEBATOR_USER
from .safe_debator import SYSTEM_PROMPT as SAFE_DEBATOR_SYSTEM, USER_TEMPLATE as SAFE_DEBATOR_USER
from .neutral_debator import SYSTEM_PROMPT as NEUTRAL_DEBATOR_SYSTEM, USER_TEMPLATE as NEUTRAL_DEBATOR_USER
from .risk_judge import SYSTEM_PROMPT as RISK_JUDGE_SYSTEM, USER_TEMPLATE as RISK_JUDGE_USER
from .signal_extractor import SYSTEM_PROMPT as SIGNAL_EXTRACTOR_SYSTEM, USER_TEMPLATE as SIGNAL_EXTRACTOR_USER

__all__ = [
    "MARKET_ANALYST_SYSTEM", "MARKET_ANALYST_USER",
    "FUNDAMENTALS_ANALYST_SYSTEM", "FUNDAMENTALS_ANALYST_USER",
    "NEWS_ANALYST_SYSTEM", "NEWS_ANALYST_USER",
    "SENTIMENT_ANALYST_SYSTEM", "SENTIMENT_ANALYST_USER",
    "BULL_RESEARCHER_SYSTEM", "BULL_RESEARCHER_USER",
    "BEAR_RESEARCHER_SYSTEM", "BEAR_RESEARCHER_USER",
    "RESEARCH_MANAGER_SYSTEM", "RESEARCH_MANAGER_USER",
    "TRADER_SYSTEM", "TRADER_USER",
    "RISKY_DEBATOR_SYSTEM", "RISKY_DEBATOR_USER",
    "SAFE_DEBATOR_SYSTEM", "SAFE_DEBATOR_USER",
    "NEUTRAL_DEBATOR_SYSTEM", "NEUTRAL_DEBATOR_USER",
    "RISK_JUDGE_SYSTEM", "RISK_JUDGE_USER",
    "SIGNAL_EXTRACTOR_SYSTEM", "SIGNAL_EXTRACTOR_USER",
]
